### ISSUE TITLE
Consider integrating noble-bls12-381？

### ISSUE THREAD

**Issue by vae520283995** [foxypool/chia-api#4]
@felixbrucker Hi felixbrucker,
Can noble-bls12-381 be integrated? All current libraries are chia-wallet based on api implementation
https://github.com/paulmillr/bls12-381-keygen
https://github.com/paulmillr/noble-bls12-381
The author of the encryption library describes that it is compatible with chia, but I am not clear about the details.
https://github.com/paulmillr/noble-bls12-381/issues/28

**Comment by felixbrucker** [comment]
Interesting, ill take a look 👍

**Comment by vae520283995** [comment]
> Interesting, ill take a look 👍

According to https://github.com/Chia-Network/bls-signatures#readme we need to modify the DST in https://github.com/paulmillr/noble-bls12-381/blob/03c992ccf78a9175c981e198bd2b256ee4745f2c/index.ts#L22 to the officially recommended Augmented
https://github.com/Chia-Network/bls-signatures/blob/main/README.md#before-you-start
https://github.com/Chia-Network/bls-signatures/blob/7cc5ae144cb2a4e54f812b1aeaaa673fbb068ac5/src/schemes.cpp#L49

**Comment by felixbrucker** [comment]
I could not find any working library for deriving child keys from the master key, did you find one?

**Comment by vae520283995** [comment]
> I could not find any working library for deriving child keys from the master key, did you find one?

https://github.com/paulmillr/bls12-381-keygen

**Comment by felixbrucker** [comment]
This seems to produce invalid child keys, same as https://github.com/ChainSafe/bls-hd-key

**Comment by vae520283995** [comment]
> This seems to produce invalid child keys, same as https://github.com/ChainSafe/bls-hd-key

How do you verify that the child keys is valid

**Comment by felixbrucker** [comment]
i know the correct public key for eg. the pool pk, getting the pk for a private key works, but the wrong child private key is generated, the resulting public key does not match the expected result.

**Comment by vae520283995** [comment]
> i know the correct public key for eg. the pool pk, getting the pk for a private key works, but the wrong child private key is generated, the resulting public key does not match the expected result.

Can you provide me with basic data? Tomorrow I will use https://github.com/Chia-Network/bls-signatures/blob/7cc5ae144c/python-impl/hd_keys.py to compare with https://github.com/paulmillr/bls12-381-keygen

**Comment by felixbrucker** [comment]
Yes, you can use these: https://github.com/Chia-Network/bls-signatures/blob/7cc5ae144cb2a4e54f812b1aeaaa673fbb068ac5/src/test.cpp#L222-L262

last time i asked in keybase the answer was that those libs might not use hardened keys, those test keys are hardened 👍

**Comment by vae520283995** [comment]
> Yes, you can use these: https://github.com/Chia-Network/bls-signatures/blob/7cc5ae144cb2a4e54f812b1aeaaa673fbb068ac5/src/test.cpp#L222-L262
> 
> last time i asked in keybase the answer was that those libs might not use hardened keys, those test keys are hardened 👍

got it, See you tomorrow🎉

**Comment by vae520283995** [comment]
https://github.com/paulmillr/bls12-381-keygen/blob/87517b5d9124676db5c4baeddde0620da25cf994/index.ts#L83
You only need to comment this line of code, it will be consistent with the key generation of https://github.com/Chia-Network/bls-signatures

**Comment by felixbrucker** [comment]
Nice!

**Comment by vae520283995** [comment]
https://github.com/Chia-Network/bls-signatures/issues/216
I feel it may be a bug in https://github.com/Chia-Network/bls-signatures

**Comment by felixbrucker** [comment]
I checked out the methods exposed by `noble-bls12-381`, so far the test data i used worked out of the box, i did not need to adjust any DST values. Do you know where those are needed to be changed?

i tested public key generation, sign, verify, aggregated signature creation and verify batch

Regarding the child  derivation i also asked in KB, waiting for a response

**Comment by vae520283995** [comment]
> I checked out the methods exposed by `noble-bls12-381`, so far the test data i used worked out of the box, i did not need to adjust any DST values. Do you know where those are needed to be changed?
https://github.com/Chia-Network/bls-signatures/blob/main/README.md#before-you-start
Official recommendation Augmented

**Comment by vae520283995** [comment]
> Regarding the child derivation i also asked in KB, waiting for a response
https://github.com/Chia-Network/bls-signatures/issues/216#issuecomment-841666132

**Comment by felixbrucker** [comment]
Check out https://github.com/felixbrucker/chia-hd-key, i added the key handling in there. If you have any problems or suggestions please let me know 👍

**Comment by vae520283995** [comment]
Hello, is the integrated chia-hd-key in this project or a new project?

**Comment by felixbrucker** [comment]
its a separate module, as currently chia-api does not expose any type info or custom types, just raw api data i didnt feel like returning custom objects in chia-api. You can however easily transform them in your code

**Comment by vae520283995** [comment]
> its a separate module, as currently chia-api does not expose any type info or custom types, just raw api data i didnt feel like returning custom objects in chia-api. You can however easily transform them in your code

I am very interested in chia's raw transaction and signature, but the current library uses api to complete the transfer. I only know that its cryptography uses bls12381, and I don’t know anything else, so I don’t know how to construct the transaction, and sign the transaction

**Comment by felixbrucker** [comment]
I'm not sure i'll implement spend bundles in here, i'll let you know when / if i do 👍 
I'll add the push_tx api call at some point in the future tho, but youd need to create the spend bundle yourself probably for the time being.

**Comment by vae520283995** [comment]
> I'm not sure i'll implement spend bundles in here, i'll let you know when / if i do 👍
> I'll add the push_tx api call at some point in the future tho, but youd need to create the spend bundle yourself probably for the time being.

Wait for good news

**Comment by felixbrucker** [comment]
It looks like using augmented scheme does not work properly, generated signatures are invalid and valid signatures are marked as invalid when verifying. Basic Schema works fine. I used `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG_` as DST label.
Do you have an idea what could be the problem @vae520283995 ? According to https://github.com/paulmillr/noble-bls12-381/issues/28 this should have been the only change i think.

**Comment by vae520283995** [comment]
> It looks like using augmented scheme does not work properly, generated signatures are invalid and valid signatures are marked as invalid when verifying. Basic Schema works fine. I used `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG_` as DST label.

What tool do you use to verify, I use noble-bls12-381 to verify that it is valid
```
Basic: BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_
priv 28b90deaf189015d3a325908c5e0e4bf00f84f7e639b056ff82d7e70b6eede4c
msg 09
sig 8647aa9680cd0cdf065b94e818ff2bb948cc97838bcee987b9bc1b76d0a0a6e0d85db4e9d75aaedfc79d4ea2733a21ae0579014de7636dd2943d45b87c82b1c66a289006b0b9767921bb8edd3f6c5c5dec0d54cd65f61513113c50cc977849e5
Augmentation: BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_AUG_
priv 28b90deaf189015d3a325908c5e0e4bf00f84f7e639b056ff82d7e70b6eede4c
msg 09
sig 9602ed712e087bc7317f6ab9a0d743ab077161808b40959e237b5d79bf5892861af0cd999939a65d48791f80e0d29d5214bf02c03e64b4e91cbdb081d26e52c9d1eba841a100d0ce2fb360aeabe8b34e242bede71a8dd42a6481f4f973ef69b2
```

**Comment by felixbrucker** [comment]
I tested against the chia wallet, which also uses augmented scheme:
```
mnemonic: stay series game wire lonely funny method fancy pitch assume silent join trust cool coconut beach taxi bus program foam lock escape review bridge
pool sk: 58363f2b5f2d81349b8bb9f96031805667cc00991e59997a21a3b769818f79d0
pool pk: a3eccbfc30f120792d23cbe445ad2dd572b7d7f745d583bc3d67a8f74ad267c3b5e8ae40bdd9910dc56f932325bc5892
msg: 09
signature with noble-bls12-381: 8164b4cade25ece30ddb91a31ab1f21c873360b356c33104cfa42aabb623ca758cef9fc7c713c48b3d7d6c5691f685690ab6def793fadc130c2965fc498b594ce68a488e44e041751cac8334367be200d6bc1e76c3d75b91a1d71571b607fe39
signature with chia wallet: b38d4cf040ecb307b95c699b8b0d393ed0c17b34e8e5338e61d95b10cb29b62b50bcdf58cf2b6f1d74cedaaf1321608b0a63c54fe8b637aea575c77d97f165a120fc22fea53e4b0f60dc0b9419a578928cc1f04e65f21326ae5eb23092eb6239
```
i used `chia keys sign -t "m/12381/8444/1/0" -d 09 -f 2957776205` to sign the message in chia cli

**Comment by vae520283995** [comment]
Why I use noble-bls12-381 and the result is different from yours
```
sk: 58363f2b5f2d81349b8bb9f96031805667cc00991e59997a21a3b769818f79d0
pk: a3eccbfc30f120792d23cbe445ad2dd572b7d7f745d583bc3d67a8f74ad267c3b5e8ae40bdd9910dc56f932325bc5892
msg: 09
sig: 816c22a4d9dd0866fa4979a0ea6225c5bff6de36cbc63c665fc195da6a37881e05317cba1b00133572d065386c450628111433d6e7fbc728aa69e2ea4418024cd47370c176278d55fe67205218793d6dd213cfc7393c453bb0c3e585d7dc440a
```

**Comment by felixbrucker** [comment]
Oh, sorry, still had some Buffer related code in there when i experimented with the chia wallet:
```js
  const signature1 = await psk.sign(Buffer.from('09', 'utf8').toString('hex'));
  const signature2 = await psk.sign('09');
  console.log('psk signature1', signature1);
  console.log('psk signature2', signature2);
```
```
psk signature1 8164b4cade25ece30ddb91a31ab1f21c873360b356c33104cfa42aabb623ca758cef9fc7c713c48b3d7d6c5691f685690ab6def793fadc130c2965fc498b594ce68a488e44e041751cac8334367be200d6bc1e76c3d75b91a1d71571b607fe39
psk signature2 816c22a4d9dd0866fa4979a0ea6225c5bff6de36cbc63c665fc195da6a37881e05317cba1b00133572d065386c450628111433d6e7fbc728aa69e2ea4418024cd47370c176278d55fe67205218793d6dd213cfc7393c453bb0c3e585d7dc440a
```
using `'09'` directly results in the same result you get, but still differs from chia wallet

**Comment by vae520283995** [comment]
> signature with chia wallet: b38d4cf040ecb307b95c699b8b0d393ed0c17b34e8e5338e61d95b10cb29b62b50bcdf58cf2b6f1d74cedaaf1321608b0a63c54fe8b637aea575c77d97f165a120fc22fea53e4b0f60dc0b9419a578928cc1f04e65f21326ae5eb23092eb6239
> ```

The result of chia wallet 's signature should be
```
a3adae4837c769eea619e56bdd409eff918ab9010e52af362f490dd93847c41f4f089e272ffbb8b46655a35dc0b8bacf09dbc9ab1d7bb57ac4233ce44f4e485cfecc2713b09878880ce64ec57dbeeace0437866036bdf574e4302f2de467bedc
```

**Comment by vae520283995** [comment]
You try this data
```
sk: 58363f2b5f2d81349b8bb9f96031805667cc00991e59997a21a3b769818f79d0
pk: a3eccbfc30f120792d23cbe445ad2dd572b7d7f745d583bc3d67a8f74ad267c3b5e8ae40bdd9910dc56f932325bc5892
msg: 7f
noble-bls12-381 sig: ae2066be51abad2b2c1a9c4e3c7b99d6152a9e3836c8042ebf6d12d8822ae7e03f1ac27e444b84596174526dfb25141f191cc62cb010688802757129c22cba594635c3d4e307bb6989dff63bd7d14086282633c04fc8b9c5a32c61d4e2b3f3ad

sk: 58363f2b5f2d81349b8bb9f96031805667cc00991e59997a21a3b769818f79d0
pk: a3eccbfc30f120792d23cbe445ad2dd572b7d7f745d583bc3d67a8f74ad267c3b5e8ae40bdd9910dc56f932325bc5892
msg: 7f
Chia-Network/bls-signatures sig:  8b5edc88ac92ea00666a1ad1883b809b7d972a2e223d9c43206aca552b2725642fc166daf9b1f8aed46a8b9c21f6c032b0b6a2867e82a904815115069d471634eac0b23060a55a566fa2ee0588101e09ac6d74afd9fa9c58ecf4e15e4aae8b70f```

**Comment by felixbrucker** [comment]
Diff from chia cli vs bls-signatures might be due to the message parsing here: https://github.com/Chia-Network/chia-blockchain/blob/280488da7d6f0a896aef38c4a96241252e1e6e2a/chia/cmds/keys_funcs.py#L118

**Comment by felixbrucker** [comment]
But still even with bls-signatures there is a diff between noble and bls-signatures

**Comment by vae520283995** [comment]
According to this draft https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-bls-signature-04#section-3.2.1, we know that Message augmentation adds the signed message to the public key when signing.

**Comment by vae520283995** [comment]
https://github.com/felixbrucker/chia-hd-key/blob/f40a841a0ae52a29b8011cb7902d697dee8ed4a1/src/private-key.ts#L38
https://github.com/felixbrucker/chia-hd-key/blob/f40a841a0ae52a29b8011cb7902d697dee8ed4a1/src/public-key.ts#L18
So you should modify these two places, when using augmented scheme
```
message = pk + message
```

**Comment by felixbrucker** [comment]
Closing here, one can use https://github.com/foxypool/chia-hd-key for key related things, and the latest noble libraries might even work out of the box (have not tried tho)
